# sparse requiring rust >= 1.68.0
[source.crates-io]
replace-with = 'ustc'

[source.aliyun]
registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[source.sjtu]
registry = "sparse+https://mirrors.sjtug.sjtu.edu.cn/crates.io-index/"

[source.ustc-dense]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
